services:
  db:
    image: mysql:8.0
    container_name: apache_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: ./php
    container_name: apache_web
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    restart: always
