services:
  db:
    image: postgres:16
    container_name: lojinha_postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - lojinha_network

  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lojinha_java
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: always
    networks:
      - lojinha_network

  nginx:
    image: nginx:latest
    container_name: lojinha_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java
    restart: always
    networks:
      - lojinha_network

volumes:
  postgres_data:

networks:
  lojinha_network:
    driver: bridge
